name: Derek Clair
favicon: null
layout_spectrum: 0.25524
typography_spectrum: 0.18998
title: A gentleman and a scholar.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5175648-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
  brandStrength: 0.6068624360486865
  lightness: 0.42605413612909615
  saturation: 0.4720598941203207
  rhythmicContrast: 0.49379075947217643
purpose: []
